### PR TITLE
HUB-17782 : Make changes to Remove the version information of Nginx in

### PR DESCRIPTION
**Pull request by kaushak**
Make changes to Remove the version information of Nginx in the header

### CODE REVIEW

**Review by bd-skatzman — APPROVED** [review]
Remember that this also will require bumping the blackduck-nginx image version and references that version change in the orchestration build within the hub-backend repository.

**Review by paykin — APPROVED** [review]

**Review by aclairekeum — APPROVED** [review]

**Comment by aclairekeum** [comment]
Please make sure the CI build and the release build has run in jenkins before updating the orchestration file changes.

**Comment by kaushak** [comment]
Please merge the changes to the master as I am not authorized to do so

**Comment by bd-skatzman** [comment]
You should have access.  Try again and let me know.

**Pull request merged**
